workflows:
  my-workflow:
    name: My workflow name
    instance_type: linux
    max_build_duration: 60
    environment:
      ndk: r23
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "RollercoinMod"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - adamkhader187@gmail.com
      scripts:
        - echo 'Post-publish script'
        
        
        
  
